- name: Install K3s agents
  hosts: backend
  become: yes
  gather_facts: true
  
  tasks:
    - name: Get master IP from inventory
      set_fact:
      master_ip: "{{ hostvars[groups['frontend'][0]]['private_ip'] }}"

    - name: Slurp token from master
      slurp:
        src: "/tmp/k3s_token.txt"
      register: slurped_token
      delegate_to: "{{ groups['frontend'][0] }}"
      run_once: true

    - name: Set token fact
      set_fact:
        k3s_token: "{{ slurped_token.content | b64decode }}"

    - name: Install K3s agent
      shell: |
         curl -sfL https://get.k3s.io | K3S_URL="https://{{ master_ip }}:6443" K3S_TOKEN="{{ k3s_token }}" sh -
      args:
        executable: /bin/bash
