- name: Deploy TeachUA Backend
  hosts: backend
  become: true
  vars:
    app_db_user: "{{ db_name }}"
    app_db_password: "{{ db_password }}"
    app_postgres_admin_user: "{{ postgres_admin_user }}"
    app_postgres_admin_password: "{{ postgres_admin_password }}"
    app_db_host: "{{ db_host }}"
    app_db_port: 5432
    dump_file: teachua_full_dump.sql
    db_name: teachua
    packages:
      - postgresql-client
      - python3-psycopg2
  roles:
    - role: backend
      vars:
        db_user: "{{ app_db_user }}"
        db_password: "{{ app_db_password }}"
        postgres_admin_user: "{{ app_postgres_admin_user }}"
        postgres_admin_password: "{{ app_postgres_admin_password }}"
        db_host: "{{ app_db_host }}"
        db_port: "{{ app_db_port }}"
